# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imagen.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imagen.proto',
  package='protocolBuffers',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cimagen.proto\x12\x0fprotocolBuffers\"\xbe\x01\n\nVideoFrame\x12\x12\n\nframe_data\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x04 \x01(\x05\x12\x10\n\x08\x65ncoding\x18\x05 \x01(\t\x12\x14\n\x0c\x66rame_number\x18\x06 \x01(\x03\x12\x11\n\ttimestamp\x18\x07 \x01(\x01\x12\x1b\n\x13\x63ompression_quality\x18\x08 \x01(\x05\x12\x13\n\x0bis_keyframe\x18\t \x01(\x08\x62\x06proto3'
)




_VIDEOFRAME = _descriptor.Descriptor(
  name='VideoFrame',
  full_name='protocolBuffers.VideoFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_data', full_name='protocolBuffers.VideoFrame.frame_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='protocolBuffers.VideoFrame.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='protocolBuffers.VideoFrame.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channels', full_name='protocolBuffers.VideoFrame.channels', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='protocolBuffers.VideoFrame.encoding', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_number', full_name='protocolBuffers.VideoFrame.frame_number', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='protocolBuffers.VideoFrame.timestamp', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compression_quality', full_name='protocolBuffers.VideoFrame.compression_quality', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_keyframe', full_name='protocolBuffers.VideoFrame.is_keyframe', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=224,
)

DESCRIPTOR.message_types_by_name['VideoFrame'] = _VIDEOFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoFrame = _reflection.GeneratedProtocolMessageType('VideoFrame', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOFRAME,
  '__module__' : 'imagen_pb2'
  # @@protoc_insertion_point(class_scope:protocolBuffers.VideoFrame)
  })
_sym_db.RegisterMessage(VideoFrame)


# @@protoc_insertion_point(module_scope)
